"""update orders table

Revision ID: 049216f87130
Revises: 4b9a7ac7e970
Create Date: 2025-08-05 19:19:25.938329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049216f87130'
down_revision = '4b9a7ac7e970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PAID', 'BOUGHT_OUT', 'AGENT', 'CUSTOMS', 'MOSCOW_WAREHOUSE', 'TO_PETERSBURG', 'TO_CUSTOMER_CITY', 'COMPLETED', 'CANCELED', name='orderstatus'), nullable=False),
    sa.Column('article', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('price_rub', sa.Float(), nullable=False),
    sa.Column('price_cny', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('type_item', sa.Enum('SHOES', 'CLOTH', name='ordertypeitem'), nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('orders_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
