"""update user table

Revision ID: 4b9a7ac7e970
Revises: 5b2571290cc4
Create Date: 2025-08-05 16:58:55.989390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9a7ac7e970'
down_revision = '5b2571290cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
