"""create referrals table

Revision ID: 5b2571290cc4
Revises: b2bb86d15c31
Create Date: 2025-08-05 16:33:27.023384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2571290cc4'
down_revision = 'b2bb86d15c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_from', sa.BIGINT(), nullable=False),
    sa.Column('id_to', sa.BIGINT(), nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_from'], ['users.id'], name=op.f('referrals_id_from_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_to'], ['users.id'], name=op.f('referrals_id_to_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('referrals_pkey')),
    sa.UniqueConstraint('id_from', 'id_to', name='unique_referral'),
    sa.UniqueConstraint('id_to', name=op.f('referrals_id_to_key'))
    )
    op.create_index('ix_user_id', 'referrals', ['id_from', 'id_to'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id', table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###
