"""create app settings table

Revision ID: 7664b3f770cc
Revises: 32e2074c3444
Create Date: 2025-08-06 17:39:49.598727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7664b3f770cc'
down_revision = '32e2074c3444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appsettings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('appsettings_pkey')),
    sa.UniqueConstraint('key', name=op.f('appsettings_key_key'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appsettings')
    # ### end Alembic commands ###
