"""create promo table

Revision ID: 963efe1c0476
Revises: 
Create Date: 2025-08-02 19:01:58.266633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963efe1c0476'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('promos_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promos')
    # ### end Alembic commands ###
