"""fix email is unique

Revision ID: e002d865c112
Revises: 7664b3f770cc
Create Date: 2025-08-12 18:35:57.439060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e002d865c112'
down_revision = '7664b3f770cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('admins_user_id_key'), 'admins', ['user_id'])
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('admins_user_id_key'), 'admins', type_='unique')
    # ### end Alembic commands ###
